version: '3.9'
services:
  server:
    build: ./server
    ports:
      - "3001:3001"
    env_file:
      - ./.env.example
  client:
    build: ./client
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3001/api
    depends_on:
      - server